# Generated by Django 5.0.2 on 2024-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_reportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_genration',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_genration')},
        ),
    ]
